---
- name: Install and  configure database
  become: true
  command: mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
- name: start mariadb service
  become: true
  systemd:
    name: mariadb
    daemon_reload: true
    enabled: true
    state: started
- name: Change root user password on first run
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root }}"
    check_implicit_admin: true
    name: root
    password: "{{ mysql_root }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
  with_items:
    - "{{ ansible_nodename }}"
    - 127.0.0.1
    - ::1
    - localhost
- name: delete anonymous MySQL server user for {{ ansible_nodename }}
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root }}"
    check_implicit_admin: true
    user: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - ""
    - "{{ ansible_nodename }}"
    - localhost
- name: remove test db
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root }}"
    name: "test"
    state: present
- name: copy mysql general configuration
  become: true
  template:
    dest: /etc/mysql/my.cnf
    src: my.cnf.j2
- name: restart mariadb service
  become: true
  systemd:
    name: mariadb
    daemon_reload: true
    state: restarted
