---
- name: start mariadb service
  become: true
  systemd:
    name: mariadb
    daemon_reload: true
    enabled: true
    state: started
  when: ansible_distribution_major_version == "18"
- name: start mariadb service
  become: true
  systemd:
    name: mysql
    daemon_reload: true
    enabled: true
    state: started
  when: ansible_distribution_major_version == "16"
- name: Change root user password on first run
  become: true
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root }}"
    check_implicit_admin: true
    name: root
    password: "{{ mysql_root }}"
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
  with_items:
    - "{{ ansible_nodename }}"
    - 127.0.0.1
    - ::1
    - localhost
- name: delete anonymous MySQL server user for {{ ansible_nodename }}
  become: true
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root }}"
    check_implicit_admin: true
    user: ""
    host: "{{ item }}"
    state: absent
  with_items:
    - ""
    - "{{ ansible_nodename }}"
    - localhost
- name: remove test db
  become: true
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root }}"
    name: "test"
    state: present
- name: copy mysql general configuration
  become: true
  template:
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    src: my-ubuntu.cnf.j2
- name: restart mariadb service
  become: true
  systemd:
    name: mariadb
    daemon_reload: true
    state: restarted
  when: ansible_distribution_major_version == "18"
- name: restart mariadb service
  become: true
  systemd:
    name: mysql
    daemon_reload: true
    state: restarted
  when: ansible_distribution_major_version == "16"
